# Generated by Django 2.2 on 2022-04-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='goals',
        ),
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
