# Generated by Django 2.2 on 2022-04-23 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220423_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='buddy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buddy', to=settings.AUTH_USER_MODEL),
        ),
    ]
