# Generated by Django 2.2 on 2022-04-22 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfReflection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('role', models.CharField(choices=[('Toastmaster', 'Toastmaster'), ('Timer', 'Timer'), ('Word of the day/Grammarian', 'Word of the day/Grammarian'), ('Toast of the day', 'Toast of the day'), ('Speaker - Prepared speech', 'Speaker - Prepared speech'), ('Evaluator', 'Evaluator'), ('Table topics master', 'Table topics master'), ('Speaker - Table topics', 'Speaker - Table topics'), ('Hark and fine', 'Hark and fine'), ('Ah counter', 'Ah counter'), ('General Evaluator', 'General Evaluator')], max_length=50)),
                ('score', models.CharField(choices=[('1-Developing', '1-Developing'), ('2-Emerging', '2-Emerging'), ('3-Accomplished', '3-Accomplished'), ('4-Excel', '4-Excel'), ('5-Exemplary', '5-Exemplary')], max_length=50)),
                ('meeting_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='BuddyFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('role', models.CharField(choices=[('Toastmaster', 'Toastmaster'), ('Timer', 'Timer'), ('Word of the day/Grammarian', 'Word of the day/Grammarian'), ('Toast of the day', 'Toast of the day'), ('Speaker - Prepared speech', 'Speaker - Prepared speech'), ('Evaluator', 'Evaluator'), ('Table topics master', 'Table topics master'), ('Speaker - Table topics', 'Speaker - Table topics'), ('Hark and fine', 'Hark and fine'), ('Ah counter', 'Ah counter'), ('General Evaluator', 'General Evaluator')], max_length=50)),
                ('score', models.CharField(choices=[('1-Developing', '1-Developing'), ('2-Emerging', '2-Emerging'), ('3-Accomplished', '3-Accomplished'), ('4-Excel', '4-Excel'), ('5-Exemplary', '5-Exemplary')], max_length=50)),
                ('meeting_date', models.DateField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-meeting_date'],
            },
        ),
    ]
