# Generated by Django 2.2 on 2022-04-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmbuddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyfeedback',
            name='role',
            field=models.CharField(choices=[('Toastmaster', 'Toastmaster'), ('Timer', 'Timer'), ('Word of the day/Grammarian', 'Word of the day/Grammarian'), ('Toast of the day', 'Toast of the day'), ('Speaker - Prepared speech', 'Speaker - Prepared speech'), ('Evaluator - Prepared speech', 'Evaluator - Prepared speech'), ('Table topics master', 'Table topics master'), ('Speaker - Table topics', 'Speaker - Table topics'), ('Evaluator - Table topics', 'Evaluator - Table topics'), ('Hark and fine', 'Hark and fine'), ('Ah counter', 'Ah counter'), ('General Evaluator', 'General Evaluator')], max_length=50),
        ),
        migrations.AlterField(
            model_name='selfreflection',
            name='role',
            field=models.CharField(choices=[('Toastmaster', 'Toastmaster'), ('Timer', 'Timer'), ('Word of the day/Grammarian', 'Word of the day/Grammarian'), ('Toast of the day', 'Toast of the day'), ('Speaker - Prepared speech', 'Speaker - Prepared speech'), ('Evaluator - Prepared speech', 'Evaluator - Prepared speech'), ('Table topics master', 'Table topics master'), ('Speaker - Table topics', 'Speaker - Table topics'), ('Evaluator - Table topics', 'Evaluator - Table topics'), ('Hark and fine', 'Hark and fine'), ('Ah counter', 'Ah counter'), ('General Evaluator', 'General Evaluator')], max_length=50),
        ),
    ]
